<a href="https://colab.research.google.com/github/srijonp4/dl/blob/main/lesson_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [16]:
tensor_zero_d = tf.constant(4)

In [17]:
import tensorflow as tf
tensor_one_d = tf.constant([-2,0,2,3,4,5],dtype=tf.float32)
tensor_one_d

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([-2.,  0.,  2.,  3.,  4.,  5.], dtype=float32)>

In [18]:
tensor_bool = tf.cast(tensor_one_d,dtype=tf.bool)
tensor_bool

<tf.Tensor: shape=(6,), dtype=bool, numpy=array([ True, False,  True,  True,  True,  True])>

In [19]:
tensor_string = tf.constant(['helllo' , 'world'])
tensor_string

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'helllo', b'world'], dtype=object)>

In [21]:
np_array = np.arange(0,25,dtype=float)
np_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [23]:
tensor_from_np_array = tf.convert_to_tensor(np_array)
tensor_from_np_array

<tf.Tensor: shape=(25,), dtype=float64, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])>

In [24]:
eye_tensor = tf.eye(
    num_rows = 3 ,
    num_columns = None ,
    batch_shape = None ,
    dtype = tf.dtypes.float32,
    name = None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [27]:
eye_tensor_2 = tf.eye(
    num_rows = 3 ,
    num_columns = 4 ,
    batch_shape = None ,
    dtype = tf.dtypes.bool,
    name = None
)
print(eye_tensor_2)

tf.Tensor(
[[ True False False False]
 [False  True False False]
 [False False  True False]], shape=(3, 4), dtype=bool)


In [29]:
eye_tensor_3 = tf.eye(
    num_rows = 3 ,
    num_columns = None ,
    batch_shape = [2,] ,
    dtype = tf.dtypes.int32,
    name = None
)
print(eye_tensor_3)

tf.Tensor(
[[[1 0 0]
  [0 1 0]
  [0 0 1]]

 [[1 0 0]
  [0 1 0]
  [0 0 1]]], shape=(2, 3, 3), dtype=int32)


In [30]:
eye_tensor_4 = tf.eye(
    num_rows = 3 ,
    num_columns = None ,
    batch_shape = [2,4] ,
    dtype = tf.dtypes.int32,
    name = None
)
print(eye_tensor_4)

tf.Tensor(
[[[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]


 [[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]], shape=(2, 4, 3, 3), dtype=int32)


In [33]:
# fill method
filled_tensor = tf.fill([2,3,5],4)
filled_tensor

<tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
array([[[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]],

       [[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]]], dtype=int32)>