<a href="https://colab.research.google.com/github/srijonp4/dl/blob/main/lesson_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [4]:
tensor_zero_d = tf.constant(4)

In [5]:
import tensorflow as tf
tensor_one_d = tf.constant([-2,0,2,3,4,5],dtype=tf.float32)
tensor_one_d

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([-2.,  0.,  2.,  3.,  4.,  5.], dtype=float32)>

In [6]:
tensor_bool = tf.cast(tensor_one_d,dtype=tf.bool)
tensor_bool

<tf.Tensor: shape=(6,), dtype=bool, numpy=array([ True, False,  True,  True,  True,  True])>

In [7]:
tensor_string = tf.constant(['helllo' , 'world'])
tensor_string

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'helllo', b'world'], dtype=object)>

In [8]:
np_array = np.arange(0,25,dtype=float)
np_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [9]:
tensor_from_np_array = tf.convert_to_tensor(np_array)
tensor_from_np_array

<tf.Tensor: shape=(25,), dtype=float64, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])>

In [10]:
eye_tensor = tf.eye(
    num_rows = 3 ,
    num_columns = None ,
    batch_shape = None ,
    dtype = tf.dtypes.float32,
    name = None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [11]:
eye_tensor_2 = tf.eye(
    num_rows = 3 ,
    num_columns = 4 ,
    batch_shape = None ,
    dtype = tf.dtypes.bool,
    name = None
)
print(eye_tensor_2)

tf.Tensor(
[[ True False False False]
 [False  True False False]
 [False False  True False]], shape=(3, 4), dtype=bool)


In [12]:
eye_tensor_3 = tf.eye(
    num_rows = 3 ,
    num_columns = None ,
    batch_shape = [2,] ,
    dtype = tf.dtypes.int32,
    name = None
)
print(eye_tensor_3)

tf.Tensor(
[[[1 0 0]
  [0 1 0]
  [0 0 1]]

 [[1 0 0]
  [0 1 0]
  [0 0 1]]], shape=(2, 3, 3), dtype=int32)


In [13]:
eye_tensor_4 = tf.eye(
    num_rows = 3 ,
    num_columns = None ,
    batch_shape = [2,4] ,
    dtype = tf.dtypes.int32,
    name = None
)
print(eye_tensor_4)

tf.Tensor(
[[[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]


 [[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 0 0]
   [0 1 0]
   [0 0 1]]]], shape=(2, 4, 3, 3), dtype=int32)


In [14]:
# fill method
filled_tensor = tf.fill([2,3,5],4)
filled_tensor

<tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
array([[[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]],

       [[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]]], dtype=int32)>

In [15]:
ones_tensor = tf.ones(shape=(5,3),dtype=tf.int16)
ones_tensor

<tf.Tensor: shape=(5, 3), dtype=int16, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)>

In [16]:
print(filled_tensor)
ones_like_tensor = tf.ones_like(filled_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]

 [[4 4 4 4 4]
  [4 4 4 4 4]
  [4 4 4 4 4]]], shape=(2, 3, 5), dtype=int32)
tf.Tensor(
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]], shape=(2, 3, 5), dtype=int32)


In [17]:
print(tf.shape(filled_tensor))

tf.Tensor([2 3 5], shape=(3,), dtype=int32)


In [18]:
print(tf.rank(filled_tensor))

tf.Tensor(3, shape=(), dtype=int32)


In [19]:
tf.size(filled_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [20]:
# crate random tensors

In [21]:
random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape=(2,3),dtype=tf.float32)
random_tensor_int = tf.cast(random_tensor, dtype=tf.int32)
random_tensor_int

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 0,  0,  0],
       [-1,  0, -1]], dtype=int32)>

#### 📔 [`probabilty playground`](https://www.acsu.buffalo.edu/~adamcunn/probability/normal.html)

In [22]:
rando = tf.random.normal(
    shape=(2,3),
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
rando

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[100.19019 ,  99.9747  , 100.33843 ],
       [100.541016,  99.697136, 100.055305]], dtype=float32)>

In [23]:
uniform_dist = tf.random.uniform(
    shape=(3,2),
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
uniform_dist

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.1467135 , 0.6247933 ],
       [0.54506266, 0.7704288 ],
       [0.2028867 , 0.9542444 ]], dtype=float32)>

In [24]:
tf.random.set_seed(42)
uniform_dist_int = tf.random.uniform(
    shape=(3,2),
    minval=0,
    maxval=3,
    dtype=tf.dtypes.int32,
    seed=42,
    name=None
)
uniform_dist_int

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 1]], dtype=int32)>

In [25]:
tf.random.set_seed(42) # setting a global seed
uniform_dist_int_2 = tf.random.uniform(
    shape=(3,2),
    minval=0,
    maxval=3,
    dtype=tf.dtypes.int32,
    seed=42,
    name=None
)
uniform_dist_int_2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 1]], dtype=int32)>

In [26]:
### Tensor Indexing

In [27]:
tensor_indexed = tf.constant([4,5,6,6,8,7,5,2])
tensor_indexed[5]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [28]:
uniform_dist_int = tf.random.uniform(
    shape=(3,2),
    minval=0,
    maxval=52,
    dtype=tf.dtypes.int32,
    seed=42,
    name=None
)
uniform_dist_int

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[28,  3],
       [47, 36],
       [34, 14]], dtype=int32)>

In [29]:
print(uniform_dist_int[1][1])

tf.Tensor(36, shape=(), dtype=int32)


In [30]:
T = tf.reshape(tf.constant(tf.range(1,25)),shape=(3,8))
T

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [31]:
print(T[1][1:8])

tf.Tensor([10 11 12 13 14 15 16], shape=(7,), dtype=int32)


In [32]:
print(T[:,0:2]) #(tensor[<rows>,<columns>])

tf.Tensor(
[[ 1  2]
 [ 9 10]
 [17 18]], shape=(3, 2), dtype=int32)


In [33]:
print(T[:,0])

tf.Tensor([ 1  9 17], shape=(3,), dtype=int32)


In [34]:
print(T[:,-1])


tf.Tensor([ 8 16 24], shape=(3,), dtype=int32)


In [35]:
print(T[0:2,:])
print(T[...,0:2])

tf.Tensor(
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]], shape=(2, 8), dtype=int32)
tf.Tensor(
[[ 1  2]
 [ 9 10]
 [17 18]], shape=(3, 2), dtype=int32)


In [36]:
T = tf.reshape(tf.constant(tf.range(1,25)),shape=(2,3,4))
T

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [37]:
print(T[0 , : ,: ])

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [38]:
print(T[0 ,0 ,: ])


tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [39]:
print(T[0 , 1 ,: ])


tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)


In [40]:
print(T[0 , : ,1 ])


tf.Tensor([ 2  6 10], shape=(3,), dtype=int32)


In [41]:
print(T[0 , : ,0:2 ])


tf.Tensor(
[[ 1  2]
 [ 5  6]
 [ 9 10]], shape=(3, 2), dtype=int32)


In [42]:
print(T[0 , 1 ,0:2 ])


tf.Tensor([5 6], shape=(2,), dtype=int32)


In [43]:
print(T[: , 1 ,0:2 ])


tf.Tensor(
[[ 5  6]
 [17 18]], shape=(2, 2), dtype=int32)


In [44]:
print(T[... , : , 1 ])


tf.Tensor(
[[ 2  6 10]
 [14 18 22]], shape=(2, 3), dtype=int32)


 ### tf.math.<...> tensorflow math lib

In [45]:
x_abs = tf.abs(tf.constant([-2,25,3.35]))
x_abs

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.  , 25.  ,  3.35], dtype=float32)>

In [46]:
tf.cast(x_abs,dtype=tf.int32)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2, 25,  3], dtype=int32)>

In [47]:
x_1 = tf.constant(tf.range(0,8))
print(x_1)
x_2 = tf.constant(tf.range(8,16))
print(x_2)
print(tf.math.divide(x_1,x_2))
print(tf.math.divide_no_nan(x_1,x_2))


tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)
tf.Tensor([ 8  9 10 11 12 13 14 15], shape=(8,), dtype=int32)
tf.Tensor(
[0.         0.11111111 0.2        0.27272727 0.33333333 0.38461538
 0.42857143 0.46666667], shape=(8,), dtype=float64)
tf.Tensor(
[0.         0.11111111 0.2        0.27272727 0.33333333 0.38461538
 0.42857143 0.46666667], shape=(8,), dtype=float64)


In [48]:
print(tf.add(x_2 ,tf.constant([2])))
print(tf.add(x_2 ,tf.constant([2])))


tf.Tensor([10 11 12 13 14 15 16 17], shape=(8,), dtype=int32)
tf.Tensor([10 11 12 13 14 15 16 17], shape=(8,), dtype=int32)


In [49]:
print(tf.maximum(x_1,x_2))

tf.Tensor([ 8  9 10 11 12 13 14 15], shape=(8,), dtype=int32)


In [50]:
B = tf.constant([
                [2, 20, 30, 3, 6],
                [3, 11, 16, 1, 8],
                [14, 45, 23, 5, 27]
                ])
tf.math.argmax(B, 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2])>

In [51]:
B = tf.constant([
                [2, 20, 30, 3, 6],
                [3, 11, 16, 1, 8],
                [14, 45, 23, 5, 27]
                ])
tf.math.argmax(B, 1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1])>

In [52]:
C = tf.constant([200, 20, 30, 3, 6])
tf.argmin(C)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [53]:
D = tf.constant([
                [2, 20, 30, 3, 6],
                [3, 11, 16, 1, 8],
                [14, 45, 23, 5, 27]
                ])
print(tf.equal(B,D))

tf.Tensor(
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]], shape=(3, 5), dtype=bool)


In [54]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)  # [[256, 65536], [9, 27]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [55]:
tensor_2d = tf.reshape(tf.constant(tf.range(1,7)),shape=(2,3))
tensor_2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [56]:
tf.math.reduce_sum(
    tensor_2d, axis=None, keepdims=False, name=None
)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [57]:
tf.math.reduce_sum(
    tensor_2d, axis=0, keepdims=False, name=None
)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [58]:
tf.math.reduce_sum(
    tensor_2d, axis=1, keepdims=True, name=None
)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 6],
       [15]], dtype=int32)>


#### Sigmoid function

![Sigmoid Formula](https://raw.githubusercontent.com/srijonp4/dl/main/Screenshot%202024-03-11%20225640.png)

In [59]:
x = tf.constant([0.0, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)



<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5      , 0.7310586, 1.       , 1.       ], dtype=float32)>

In [61]:
# top K

result = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1],
                        k=3)
result.values.numpy()
result.indices.numpy()


array([5, 2, 9], dtype=int32)

In [64]:
C  = tf.constant([[1, 2, 3],
       [4, 5, 6],
      [7,8,9]])
C

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [72]:
result  = tf.math.top_k(C,k=2,sorted=False)
print(result.values.numpy())
result.indices.numpy()

[[2 3]
 [5 6]
 [8 9]]


array([[1, 2],
       [1, 2],
       [1, 2]], dtype=int32)

# tf.linalg.<....>

In [74]:
# matmul
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
print(a)  # 2-D tensor



b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
print(b ) # 2-D tensor




c = tf.matmul(a, b)
print(c ) # `a` * `b`

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [75]:
a = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3])
print(a)  # 3-D tensor


print("..................")


b = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])
print(b)  # 3-D tensor
print("..................")







c = tf.matmul(a, b)
print(c)  # `a` * `b`
print("..................")

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
..................
tf.Tensor(
[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]], shape=(2, 3, 2), dtype=int32)
..................
tf.Tensor(
[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]], shape=(2, 2, 2), dtype=int32)
..................


In [77]:
d= tf.constant(np.arange(1,7),shape=(2,3))
d

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [78]:
e= tf.constant(np.arange(1,7),shape=(2,3))
e


<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [81]:
# tf.matmul(e,d)#cant multiply

In [82]:
tf.matmul(tf.transpose(e),d)#cant multiply


<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])>

In [90]:
tf.matmul(
    d, e ,transpose_a=False,transpose_b=True,adjoint_a=False,adjoint_b=False,
    a_is_sparse=False , b_is_sparse=False , output_type=None ,name=None
)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[14, 32],
       [32, 77]])>

In [87]:
d

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [91]:
tf.matmul(
    d, e ,transpose_a=True,transpose_b=False,adjoint_a=False,adjoint_b=False,
    a_is_sparse=False , b_is_sparse=False , output_type=None ,name=None
)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])>

In [92]:
d@tf.transpose(e)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[14, 32],
       [32, 77]])>

In [101]:

b = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])
print(b)  # 3-D tensor
c= tf.constant(np.arange(1,13,dtype=np.int32),shape=[2,2,3])
print(c)
tf.linalg.matmul(b,c)

tf.Tensor(
[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 69,  96, 123],
        [ 79, 110, 141],
        [ 89, 124, 159]],

       [[333, 372, 411],
        [367, 410, 453],
        [401, 448, 495]]], dtype=int32)>

The band part is computed as follows: Assume input has k dimensions [I, J, K, ..., M, N], then the output is a tensor with the same shape where

band[i, j, k, ..., m, n] = in_band(m, n) * input[i, j, k, ..., m, n].

The indicator function

in_band(m, n) = (num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper).

In [103]:
input = tf.constant([[ 0,  1,  2, 3],
[-1,  0,  1, 2],
[-2, -1,  0, 1],
[-3, -2, -1, 0]])
print(input)

print(tf.linalg.band_part(input,num_lower=1, num_upper=-1))

print(tf.linalg.band_part(input, 2, 1))

tf.Tensor(
[[ 0  1  2  3]
 [-1  0  1  2]
 [-2 -1  0  1]
 [-3 -2 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  1  2  3]
 [-1  0  1  2]
 [ 0 -1  0  1]
 [ 0  0 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  1  0  0]
 [-1  0  1  0]
 [-2 -1  0  1]
 [ 0 -2 -1  0]], shape=(4, 4), dtype=int32)


In [104]:
print(tf.linalg.band_part(input, 0, -1)) # Upper triangular part.
print(tf.linalg.band_part(input, -1, 0)) # Lower triangular part.
print(tf.linalg.band_part(input, 0, 0))  # Diagonal

tf.Tensor(
[[0 1 2 3]
 [0 0 1 2]
 [0 0 0 1]
 [0 0 0 0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  0  0  0]
 [-1  0  0  0]
 [-2 -1  0  0]
 [-3 -2 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


In [113]:
sq_mat = tf.constant(np.arange(1,5),shape=(2,2),dtype=tf.float32
                     )
print(sq_mat)
# to get the inverse the matrix has to be a square matrix
tf.linalg.inv(sq_mat)


tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [115]:
# inv of a matrix * the matrix itself  === iddentity matrix

sq_mat@tf.linalg.inv(sq_mat)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.0000000e+00,  0.0000000e+00],
       [-4.7683716e-07,  1.0000002e+00]], dtype=float32)>

In [117]:
# svd of tensor
s ,v , d = tf.linalg.svd(sq_mat)
print(s,v,d)

tf.Tensor([5.4649854  0.36596614], shape=(2,), dtype=float32) tf.Tensor(
[[ 0.4045535 -0.9145143]
 [ 0.9145143  0.4045535]], shape=(2, 2), dtype=float32) tf.Tensor(
[[ 0.5760484  0.8174156]
 [ 0.8174156 -0.5760484]], shape=(2, 2), dtype=float32)


# tf.insum

In [119]:
m0 = tf.random.normal(shape=[2, 3])
print(m0)
m1 = tf.random.normal(shape=[3, 5])
print(m1)




tf.Tensor(
[[ 0.3274685 -0.8426258  0.3194337]
 [-1.4075519 -2.3880599 -1.0392479]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 8.4224582e-02 -8.6090374e-01  3.7812304e-01 -5.1962738e-03
  -4.9453196e-01]
 [ 6.1781919e-01 -3.3082047e-01 -1.3840806e-03 -4.2373410e-01
  -1.3872087e+00]
 [-1.5488191e+00 -5.3198391e-01 -4.4756433e-01 -2.0115814e+00
  -5.7926011e-01]], shape=(3, 5), dtype=float32)


In [120]:
e = tf.einsum('ij,jk->ik', m0, m1)

In [121]:
print(e)

tf.Tensor(
[[-0.98775446 -0.1730946  -0.01797747 -0.2872192   0.82191896]
 [ 0.0156672   2.5546489  -0.06379229  3.1097481   4.6108117 ]], shape=(2, 5), dtype=float32)


In [122]:
print(e.shape)

(2, 5)


In [129]:
m0 = tf.random.uniform(
    minval=5,
    maxval=52,
    dtype=tf.dtypes.int32,
    seed=42,
    name=None,
    shape=( 3,5))
print(m0)
m1 = tf.random.uniform(minval=5,maxval=25,dtype=tf.dtypes.int32,shape=[3, 5])
print(m1)

tf.Tensor(
[[13 35 36 16 44]
 [23 23 45 34 50]
 [43  7 23  8 36]], shape=(3, 5), dtype=int32)
tf.Tensor(
[[19 15  9  9  7]
 [15 17 17  7 18]
 [20 11 12 24  6]], shape=(3, 5), dtype=int32)


In [139]:
# hardamond & elementwise
e0  = tf.einsum('ij,ij->ij',m0,m1)
print(e0)

tf.Tensor(
[[247 525 324 144 308]
 [345 391 765 238 900]
 [860  77 276 192 216]], shape=(3, 5), dtype=int32)


In [136]:
13*19

247

In [138]:
e0T = tf.einsum('ij->ji',e0)
print(e0T)

tf.Tensor(
[[247 345 860]
 [525 391  77]
 [324 765 276]
 [144 238 192]
 [308 900 216]], shape=(5, 3), dtype=int32)


In [140]:
# working with 3d arrays